---
# tasks file for rpi-config > base

- name: Upgrade distribution
  apt:
    update_cache=yes
    upgrade=safe
    cache_valid_time=1800
  when: raspberry_pi_update_packages

- name: Reboot
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait for Raspberry PI to come back
  become: false
  local_action: wait_for
  args:
      host: "{{ ansible_host }}"
      port: "{{ ansible_ssh_port }}"
      state: started
      delay: 10

- name: Install base packages
  apt:
    pkg="{{ item }}"
    state=latest
  with_items:
    - "{{ apt_base_packages }}"
