---
- name: Set hostname
  hostname:
    name: "{{ ansible_host }}"

- name: Configure options in /boot/config.txt.
  lineinfile:
    dest: /boot/config.txt
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertafter: EOF
    state: present
  with_items: "{{ raspberry_pi_boot_config_options }}"
  notify:
    - apply raspi-config
    - reboot

- name: Configure options in /etc/rc.local.
  lineinfile:
    dest: /etc/rc.local
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertbefore: "^exit"
    state: present
  with_items: "{{ raspberry_pi_rc_local_options }}"
  notify:
    - apply raspi-config
    - reboot

- name: Disable bluetooth LE
  systemd:
    name: bluetooth
    enabled: no
    state: stopped
  when: not raspberry_pi_enable_bluetooth
  tags:
    - bluetooth

- name: Enable bluetooth LE
  systemd:
    name: bluetooth
    enabled: yes
    state: started
  when: raspberry_pi_enable_bluetooth
  tags:
    - bluetooth

- name: Disable I2C
  shell: "raspi-config nonint do_i2c 1"
  when: not raspberry_pi_enable_i2c

- name: Enable I2C
  shell: "raspi-config nonint do_i2c 0"
  when: raspberry_pi_enable_i2c

- name: Disable SPI
  shell: "raspi-config nonint do_spi 1"
  when: not raspberry_pi_enable_spi

- name: Enable SPI
  shell: "raspi-config nonint do_spi 0"
  when: raspberry_pi_enable_spi

- name: Disable OneWire
  shell: "raspi-config nonint do_onewire 1"
  when: not raspberry_pi_enable_onewire

- name: Enable OneWire
  shell: "raspi-config nonint do_onewire 0"
  when: raspberry_pi_enable_onewire

- name: Disable Serial
  shell: "raspi-config nonint do_serial 1"
  when: not raspberry_pi_enable_serial

- name: Enable Serial
  shell: "raspi-config nonint do_serial 0"
  when: raspberry_pi_enable_serial
